proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 9500
  authentication: simple
  admin-groups: scientists
  docker:
      internal-networking: true
  users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
  specs:
    - id: rnaseq
      display-name: RNA Seq
      description: Application to demonstrate RNA Seq results
      container-image: atgenomix.azurecr.io/atgenomix/runtime/shiny-app:2024-09-21-09-00
      container-cmd: ["R", "-q", "-e", "rnaseq::runShiny()"]
      container-network: shiny-proxy-net
      container-volumes: [ "/home/spark-current:/home/spark-current", "/mnt:/mnt" ]
logging:
  file:
    name: shinyproxy.log